### ISSUE TITLE
请问php中如何使用workerman服务，想增加php端口貌似不支持

### ISSUE THREAD

**Issue by nihaoniu** [imeepo/dnmp#1]
请问php中如何使用workerman服务，想增加php端口貌似不支持

**Comment by imeepo** [comment]
## 1、增加一条docker-compose配置
首先你需要去docker-compose-example.yml，复制一份你想用的PHP版本，

比如我想用PHP8.1版本，下面是复制出来的配置(记得修改端口号，6666端口号是容器外的，9999端口号是容器内的，也就是你workerman的端口号)
```
# +---------------------+ #
#       Webman 项目
# +---------------------+ #
  webman-api:
    build:
      context: ${SERVICE_DIR}/php
      args:
        PHP_VERSION: ${PHP_81_VERSION}
        ALPINE_MIRRORS_URL: ${ALPINE_MIRRORS_URL}
        TZ: "$TZ"
        PHP_EXTENSIONS: ${PHP_81_EXTENSIONS}
        PHP_INSTALL_COMPOSER: ${PHP_81_INSTALL_COMPOSER}
    ports:
      - "6666:9999"
    volumes:
      - ${SOURCE_DIR}:/www
      - ${PHP_81_PHP_CONF_FILE}:/usr/local/etc/php/php.ini
      - ${PHP_81_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      - ${LOGS_DIR}/php/8.1:/var/log/php
    cap_add:
      - SYS_PTRACE
    restart: always
    image: ${DOCKER_HUB_USERNAME}/php:${PHP_81_VERSION}-fpm-alpine
    container_name: webman-api
```

然后按照正常步骤生成这个webman-api容器

## 2、进入到容器里
```bash
docker exec -it webman-api sh
```
然后 ```cd``` 进入到你项目的目录

我用的是webman，所以就直接用下面这个命令启动了

```bash
php webman start -d
```

## 3、（可选）安装screen，可以保持后台运行你的项目
我那个项目加个-d参数就可以后台运行了，所以这一步其实可以省略
```bash
yum -y install screen
```
安装好之后创建一个窗口
这里就不再讲screen的命令了，你可以去网上搜一下

```bash
screen -R webman-api
```

然后再去执行第二步骤进入容器的操作就可以了

后台运行的话 ```Ctrl+A+D```
